select 1;
select 1;
abcccc sjajajdwqd
SHOW DATABASES;
SELECT *
FROM CICD.SCHEMACHANGE.CHANGE_HISTORY
ORDER BY APPLIED_AT DESC;


SHOW SCHEMAS LIKE 'DEMO_SCHEMA';
SHOW TABLES IN DEMO_SCHEMA;
USE ROLE ACCOUNTADMIN;
USE DATABASE CICD;

-- 1) Check the demo schema
SHOW SCHEMAS LIKE 'DEMO_SCHEMA';

-- 2) Check the tables inside that schema
SHOW TABLES IN DEMO_SCHEMA;

-- 3) Check schemachange history (what migrations ran)
SHOW TABLES IN SCHEMACHANGE;

SELECT *
FROM SCHEMACHANGE.CHANGE_HISTORY
ORDER BY APPLIED_AT DESC;
DESC TABLE CICD_PROD.PUBLIC.DEMO_TABLE;
