CREATE OR REPLACE TABLE DEMO_SCHEMA.PAYMENTS (
    PAYMENT_ID    NUMBER,
    ORDER_ID      NUMBER,
    PAYMENT_DATE  TIMESTAMP_NTZ,
    METHOD        STRING,
    AMOUNT        NUMBER(10,2)
);

desc table DEMO_SCHEMA.PAYMENTS;


SELECT VERSION, DESCRIPTION, *
FROM SCHEMACHANGE.CHANGE_HISTORY